// <auto-generated />
using System;
using BusStation_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusStation_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924232451_WidenRouteName")]
    partial class WidenRouteName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusStation_API.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BoardingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("BoardingTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Seat")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Boardings");
                });

            modelBuilder.Entity("BusStation_API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "Indi",
                            CityName = "Indianopolis",
                            State = "MG"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "Udia",
                            CityName = "Uberlandia",
                            State = "MG"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "Reri",
                            CityName = "Araguari",
                            State = "MG"
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "Ura",
                            CityName = "Uberaba",
                            State = "MG"
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("integer");

                    b.Property<int>("Kilometers")
                        .HasColumnType("integer");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Distances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationCityId = 2,
                            Kilometers = 60,
                            OriginCityId = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinationCityId = 1,
                            Kilometers = 60,
                            OriginCityId = 2
                        },
                        new
                        {
                            Id = 3,
                            DestinationCityId = 3,
                            Kilometers = 45,
                            OriginCityId = 2
                        },
                        new
                        {
                            Id = 4,
                            DestinationCityId = 2,
                            Kilometers = 45,
                            OriginCityId = 3
                        },
                        new
                        {
                            Id = 5,
                            DestinationCityId = 4,
                            Kilometers = 100,
                            OriginCityId = 2
                        },
                        new
                        {
                            Id = 6,
                            DestinationCityId = 2,
                            Kilometers = 100,
                            OriginCityId = 4
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceId")
                        .HasColumnType("integer");

                    b.Property<float>("PricePerKm")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DistanceId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceId = 1,
                            PricePerKm = 0.5f
                        },
                        new
                        {
                            Id = 2,
                            DistanceId = 2,
                            PricePerKm = 0.5f
                        },
                        new
                        {
                            Id = 3,
                            DistanceId = 3,
                            PricePerKm = 0.35f
                        },
                        new
                        {
                            Id = 4,
                            DistanceId = 4,
                            PricePerKm = 0.35f
                        },
                        new
                        {
                            Id = 5,
                            DistanceId = 5,
                            PricePerKm = 0.9f
                        },
                        new
                        {
                            Id = 6,
                            DistanceId = 6,
                            PricePerKm = 0.9f
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BusStation_API.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistanceId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BoardingDate")
                        .HasColumnType("date");

                    b.Property<int>("BoardingId")
                        .HasColumnType("integer");

                    b.Property<float>("FarePaid")
                        .HasColumnType("real");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardingId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BusStation_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.HasOne("BusStation_API.Entities.Route", "Routes")
                        .WithMany("Boardings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.HasOne("BusStation_API.Entities.City", "DestinationCity")
                        .WithMany("DestinationCities")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation_API.Entities.City", "OriginCity")
                        .WithMany("OriginCities")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("BusStation_API.Entities.Price", b =>
                {
                    b.HasOne("BusStation_API.Entities.Distance", "Distance")
                        .WithMany("Prices")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("BusStation_API.Entities.RefreshToken", b =>
                {
                    b.HasOne("BusStation_API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusStation_API.Entities.Route", b =>
                {
                    b.HasOne("BusStation_API.Entities.Distance", "Distance")
                        .WithMany("Routes")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("BusStation_API.Entities.Ticket", b =>
                {
                    b.HasOne("BusStation_API.Entities.Boarding", "Boarding")
                        .WithMany("Tickets")
                        .HasForeignKey("BoardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation_API.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boarding");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BusStation_API.Entities.City", b =>
                {
                    b.Navigation("DestinationCities");

                    b.Navigation("OriginCities");
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.Route", b =>
                {
                    b.Navigation("Boardings");
                });

            modelBuilder.Entity("BusStation_API.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
