// <auto-generated />
using System;
using BusStation_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusStation_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724141408_MockCities")]
    partial class MockCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BoardingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seat")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Boardings");
                });

            modelBuilder.Entity("BusStation_API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "Indi",
                            CityName = "Indianopolis",
                            State = "MG"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "Udia",
                            CityName = "Uberlandia",
                            State = "MG"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "Reri",
                            CityName = "Araguari",
                            State = "MG"
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "Ura",
                            CityName = "Uberaba",
                            State = "MG"
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityAcronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityAcronym = "",
                            CityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityAcronym = "",
                            CityId = 2
                        },
                        new
                        {
                            Id = 3,
                            CityAcronym = "",
                            CityId = 3
                        },
                        new
                        {
                            Id = 4,
                            CityAcronym = "",
                            CityId = 4
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int>("Kilometers")
                        .HasColumnType("integer");

                    b.Property<int>("OriginId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Distances");
                });

            modelBuilder.Entity("BusStation_API.Entities.Origin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityAcronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Origins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityAcronym = "",
                            CityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityAcronym = "",
                            CityId = 2
                        },
                        new
                        {
                            Id = 3,
                            CityAcronym = "",
                            CityId = 3
                        },
                        new
                        {
                            Id = 4,
                            CityAcronym = "",
                            CityId = 4
                        });
                });

            modelBuilder.Entity("BusStation_API.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceId")
                        .HasColumnType("integer");

                    b.Property<float>("PricePerKm")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DistanceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("BusStation_API.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoardingId");

                    b.HasIndex("DistanceId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("FarePaid")
                        .HasColumnType("real");

                    b.Property<DateTime>("PurchasedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BusStation_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.HasOne("BusStation_API.Entities.Ticket", "Ticket")
                        .WithOne("Boarding")
                        .HasForeignKey("BusStation_API.Entities.Boarding", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BusStation_API.Entities.Destination", b =>
                {
                    b.HasOne("BusStation_API.Entities.City", "City")
                        .WithMany("Destinations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.HasOne("BusStation_API.Entities.Destination", "Destination")
                        .WithMany("Distances")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation_API.Entities.Origin", "Origin")
                        .WithMany("Distances")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("BusStation_API.Entities.Origin", b =>
                {
                    b.HasOne("BusStation_API.Entities.City", "City")
                        .WithMany("Origins")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation_API.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.Navigation("City");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("BusStation_API.Entities.Price", b =>
                {
                    b.HasOne("BusStation_API.Entities.Distance", "Distance")
                        .WithMany("Prices")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("BusStation_API.Entities.Route", b =>
                {
                    b.HasOne("BusStation_API.Entities.Boarding", "Boarding")
                        .WithMany("Routes")
                        .HasForeignKey("BoardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusStation_API.Entities.Distance", "Distance")
                        .WithMany("Routes")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boarding");

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("BusStation_API.Entities.Ticket", b =>
                {
                    b.HasOne("BusStation_API.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusStation_API.Entities.Boarding", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.City", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Origins");
                });

            modelBuilder.Entity("BusStation_API.Entities.Destination", b =>
                {
                    b.Navigation("Distances");
                });

            modelBuilder.Entity("BusStation_API.Entities.Distance", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("BusStation_API.Entities.Origin", b =>
                {
                    b.Navigation("Distances");
                });

            modelBuilder.Entity("BusStation_API.Entities.Ticket", b =>
                {
                    b.Navigation("Boarding");
                });

            modelBuilder.Entity("BusStation_API.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
